# Generated by Django 3.2.9 on 2021-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_reference_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='new_zotero',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
