# Generated by Django 3.2.9 on 2021-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20211203_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
