# Generated by Django 3.2.9 on 2021-12-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_reference__reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='pass_or_fail',
            field=models.CharField(choices=[('PASS', 'Approved'), ('FAIL', 'Rejected')], default='FAIL', max_length=5),
        ),
    ]
