# Generated by Django 3.2.9 on 2021-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_reference_pass_or_fail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='_fail',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='pass_or_fail',
        ),
        migrations.AlterField(
            model_name='reference',
            name='certainty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='creator',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='gs_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
