# Generated by Django 3.2.9 on 2021-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20211206_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='new_zotero',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
