# Generated by Django 3.2.9 on 2021-12-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_alter_reference__reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='_pass',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
