# Generated by Django 3.2.9 on 2021-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_alter_reference_new_zotero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
