# Generated by Django 3.2.9 on 2021-12-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_auto_20211215_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
