# Generated by Django 3.2.9 on 2023-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_alter_reference_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_text', models.TextField()),
                ('polity', models.CharField(max_length=20)),
                ('creators', models.CharField(blank=True, max_length=60, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('certainty', models.IntegerField(blank=True, default=0, null=True)),
                ('wiki_number', models.IntegerField(blank=True, default=0, null=True)),
                ('browser_number', models.IntegerField(blank=True, default=0, null=True)),
                ('site', models.CharField(blank=True, choices=[('wiki', 'Seshat.info'), ('browser', 'seshatdatabank.info')], max_length=8, null=True)),
                ('done', models.BooleanField(default=False, null=True)),
                ('zotero', models.CharField(blank=True, default='--------', max_length=300, null=True)),
            ],
            options={
                'db_table': 'citations',
            },
        ),
    ]
