# Generated by Django 3.2.9 on 2023-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0021_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='child_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
