# Generated by Django 3.2.9 on 2023-03-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_citation_child_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='child_count',
        ),
    ]
