# Generated by Django 3.2.9 on 2023-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_remove_citation_child_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='child_count_browser',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='child_count_wiki',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
