# Generated by Django 3.2.9 on 2023-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0024_auto_20230313_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='citation_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
